using System.Text.Json;

namespace Qeli.Shared.Protocol;

/// <summary>
/// Checks this implementation's data-plane nonce derivation (M6) against the SHARED
/// cross-language fixture <c>conformance/prp-nonce.json</c> — the same file the Rust and
/// Swift suites read. The fixture is GENERATED by the Rust canon
/// (<c>qeli/src/gen_conformance_main.rs</c>); a hand-written vector would only prove that
/// the author and the code agree on the same mistake.
///
/// WHY: M6 (a counter-derived PRP nonce replacing a random 96-bit one) shipped in Rust,
/// C# and Swift but was silently MISSED on Android for a whole release, because nothing
/// compared the implementations. This file is the retained C# half of the comparison.
///
/// Interop note: the nonce travels on the wire and the receiver never inverts the PRP, so
/// the transform is one-sided — the peer does not need the same key. The fixture supplies
/// the key as an explicit input and pins the FUNCTION.
/// </summary>
public static class PrpNonceConformance
{
    /// <summary>
    /// Run every fixture case, reporting each through <paramref name="check"/> (name, passed).
    ///
    /// Returns false only when the fixtures could not be run at all. A shipped app has no
    /// repository next to it, so a missing fixture file is a SKIP rather than a failure —
    /// except when <c>QELI_CONFORMANCE_REQUIRED=1</c>, which CI sets so that a fixture file
    /// that moved cannot turn the gate into a silent no-op.
    /// </summary>
    public static bool Run(Action<string, bool> check)
    {
        var path = FindFixtures();
        if (path == null)
        {
            bool required = Environment.GetEnvironmentVariable("QELI_CONFORMANCE_REQUIRED") == "1";
            check("prp-nonce conformance fixtures found (conformance/prp-nonce.json)", !required);
            if (!required)
                Console.WriteLine("  [SKIP] prp-nonce conformance — fixtures not found (not running from a source tree)");
            return !required;
        }

        JsonDocument doc;
        try
        {
            doc = JsonDocument.Parse(File.ReadAllText(path));
        }
        catch (Exception e)
        {
            check($"prp-nonce conformance fixtures parse ({e.Message})", false);
            return false;
        }

        using (doc)
        {
            var root = doc.RootElement;

            // A platform listed in the fixture MUST actually run it — otherwise a renamed
            // primitive or a moved file leaves this green having verified nothing, which is
            // the exact failure mode the fixtures exist to prevent.
            bool listed = false;
            if (root.TryGetProperty("platforms", out var platforms))
                foreach (var p in platforms.EnumerateArray())
                    if (p.GetString() == "csharp") listed = true;
            if (!Report("prp-nonce conformance: csharp listed in `platforms`", listed, check))
                return false;

            int cases = 0;
            foreach (var c in root.GetProperty("cases").EnumerateArray())
            {
                cases++;
                string name = c.GetProperty("name").GetString() ?? "?";
                var key = Unhex(c.GetProperty("key").GetString()!);
                var seed = Unhex(c.GetProperty("seed").GetString()!);
                long counter = c.GetProperty("counter").GetInt64();

                // Rebuild `raw` from seed+counter rather than trusting the field: this pins
                // the seed‖counter_be LAYOUT independently of the permutation. A port can be
                // right about the Feistel network and wrong about what it permutes.
                var raw = PacketCodec.RawNonce(seed, counter);
                Report($"prp-nonce[{name}]: raw layout (seed || counter_be)",
                    Hex(raw) == c.GetProperty("raw").GetString(), check);

                Report($"prp-nonce[{name}]: permuted nonce",
                    Hex(PacketCodec.PrpNonce(key, raw)) == c.GetProperty("nonce").GetString(), check);
            }

            Report($"prp-nonce conformance: {cases} case(s) ran", cases > 0, check);
            return cases > 0;
        }
    }

    private static bool Report(string label, bool ok, Action<string, bool> check)
    {
        check(label, ok);
        return ok;
    }

    private static string Hex(byte[] b) => Convert.ToHexString(b).ToLowerInvariant();

    private static byte[] Unhex(string s) => Convert.FromHexString(s);

    /// <summary>
    /// Walk up from the working directory looking for <c>conformance/prp-nonce.json</c>,
    /// rather than hardcoding a depth — the selftest runs from different directories on
    /// Windows and macOS, and a wrong fixed path would silently find nothing.
    /// </summary>
    private static string? FindFixtures()
    {
        var env = Environment.GetEnvironmentVariable("QELI_CONFORMANCE_FIXTURES_DIR");
        if (!string.IsNullOrEmpty(env))
        {
            var p = Path.Combine(env, "prp-nonce.json");
            if (File.Exists(p)) return p;
        }

        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir != null)
        {
            var candidate = Path.Combine(dir.FullName, "conformance", "prp-nonce.json");
            if (File.Exists(candidate)) return candidate;
            dir = dir.Parent;
        }
        return null;
    }
}
