import XCTest
@testable import Qeli

/// Cross-implementation conformance for the data-plane nonce (M6).
///
/// Reads the SAME fixture as the Rust and retained C# suites (`conformance/prp-nonce.json`
/// at the repository root), which is GENERATED by the Rust canon
/// (`qeli/src/gen_conformance_main.rs`) — a hand-written vector would only prove that the
/// author and the code agree on the same mistake.
///
/// WHY: M6 (a counter-derived PRP nonce replacing a random 96-bit one) shipped in Rust, C#
/// and Swift but was silently MISSED on Android for a whole release, because nothing
/// compared the independently maintained implementations against a common table.
///
/// Interop note: the nonce travels on the wire and the receiver never inverts the PRP, so
/// the transform is one-sided — the peer does not need the same key. The fixture supplies
/// the key as an explicit input and pins the FUNCTION.
final class PrpNonceConformanceTests: XCTestCase {

    /// Locate the fixture by walking up from THIS source file rather than from a bundle
    /// resource: the file is shared with three other languages and deliberately lives
    /// outside the Xcode project, and `#filePath` is stable regardless of where the test
    /// runner's working directory happens to be.
    private func fixtures() throws -> [String: Any] {
        var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<8 {
            let candidate = dir.appendingPathComponent("conformance/prp-nonce.json")
            if FileManager.default.fileExists(atPath: candidate.path) {
                let data = try Data(contentsOf: candidate)
                guard let obj = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                    throw VPNConfigError.invalid("fixtures are not a JSON object")
                }
                return obj
            }
            dir = dir.deletingLastPathComponent()
        }
        XCTFail("conformance/prp-nonce.json not found walking up from \(#filePath)")
        throw VPNConfigError.invalid("fixtures not found")
    }

    private func hex(_ d: Data) -> String { d.map { String(format: "%02x", $0) }.joined() }

    private func unhex(_ s: String) throws -> Data {
        var out = Data()
        var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            guard let b = UInt8(s[i..<j], radix: 16) else {
                throw VPNConfigError.invalid("bad hex in fixture: \(s)")
            }
            out.append(b)
            i = j
        }
        return out
    }

    func testMatchesTheSharedCrossLanguageVectors() throws {
        let fx = try fixtures()

        // A platform listed in the fixture MUST actually run it — otherwise a renamed
        // primitive or a moved file leaves this green having verified nothing, the exact
        // failure mode the fixtures exist to prevent.
        let platforms = fx["platforms"] as? [String] ?? []
        XCTAssertTrue(platforms.contains("swift"),
                      "swift is not listed in `platforms` of prp-nonce.json")

        let cases = fx["cases"] as? [[String: Any]] ?? []
        XCTAssertFalse(cases.isEmpty, "fixture file has no cases")

        for c in cases {
            let name = c["name"] as? String ?? "?"
            let key = try unhex(c["key"] as! String)
            let seed = try unhex(c["seed"] as! String)
            // The fixture stores the counter as a JSON number; i64::MAX round-trips exactly
            // through NSNumber's 64-bit integer representation.
            let counter = UInt64((c["counter"] as! NSNumber).uint64Value)

            // Rebuild `raw` from seed+counter rather than trusting the field: this pins the
            // seed‖counter_be LAYOUT independently of the permutation. A port can be right
            // about the Feistel network and wrong about what it permutes.
            let raw = PacketCodec.rawNonce(seed: seed, counter: counter)
            XCTAssertEqual(hex(raw), c["raw"] as! String,
                           "case \(name): raw nonce layout (seed || counter_be)")

            XCTAssertEqual(hex(PacketCodec.prpNonce(key: key, raw: raw)), c["nonce"] as! String,
                           "case \(name): permuted nonce")
        }
    }
}
