import XCTest
@testable import Qeli

/// Wire-codec conformance against the SHARED cross-language fixtures
/// `conformance/packet-decode.json` and `conformance/replay-window.json`, both GENERATED by
/// the Rust canon (`qeli/src/gen_conformance_main.rs`).
///
/// WHY: retained record/window primitives exist independently in Rust, C# and Swift.
/// Decoding is deterministic given (key, record), so it pins with no test seam;
/// the window is pure state, so it pins as a table of verdicts. Before these fixtures nothing
/// compared the implementations — which is how the M6 nonce fix once shipped inconsistently.
final class WireConformanceTests: XCTestCase {

    /// Walk up from THIS source file: the fixtures are shared with Rust and retained C# and
    /// deliberately live outside the Xcode project, and `#filePath` is stable regardless of
    /// the test runner's working directory.
    private func fixture(_ name: String) throws -> [String: Any] {
        var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<8 {
            let candidate = dir.appendingPathComponent("conformance/\(name)")
            if FileManager.default.fileExists(atPath: candidate.path) {
                let data = try Data(contentsOf: candidate)
                guard let obj = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                    throw VPNConfigError.invalid("fixtures are not a JSON object")
                }
                return obj
            }
            dir = dir.deletingLastPathComponent()
        }
        XCTFail("conformance/\(name) not found walking up from \(#filePath)")
        throw VPNConfigError.invalid("fixtures not found")
    }

    private func hex(_ d: Data) -> String { d.map { String(format: "%02x", $0) }.joined() }

    private func unhex(_ s: String) throws -> Data {
        var out = Data()
        var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            guard let b = UInt8(s[i..<j], radix: 16) else {
                throw VPNConfigError.invalid("bad hex in fixture: \(s)")
            }
            out.append(b)
            i = j
        }
        return out
    }

    /// A platform listed in the fixture MUST run it — a green test that skipped is the exact
    /// failure these fixtures exist to prevent.
    private func requireListed(_ fx: [String: Any], _ label: String) {
        let platforms = fx["platforms"] as? [String] ?? []
        XCTAssertTrue(platforms.contains("swift"), "swift is not listed in `platforms` of \(label)")
    }

    func testDecodesEverySharedRecordVector() throws {
        let fx = try fixture("packet-decode.json")
        requireListed(fx, "packet-decode.json")

        let cases = fx["cases"] as? [[String: Any]] ?? []
        XCTAssertFalse(cases.isEmpty, "fixture file has no cases")

        for c in cases {
            let name = c["name"] as? String ?? "?"
            let key = try unhex(c["key"] as! String)
            let record = try unhex(c["record"] as! String)
            let raw = (c["framing"] as? String) == "raw"
            let expect = c["expect"] as! [String: Any]

            // A fresh codec per case: every record carries counter 0, so the cases are
            // independent and a replay rejection can never mask a decode failure.
            let codec = PacketCodec(cipher: try PacketCipher(key: key), rawFraming: raw)

            if (expect["reject"] as? Bool) == true {
                XCTAssertThrowsError(try codec.decrypt(record),
                                     "case \(name): a corrupt/truncated record was ACCEPTED")
            } else {
                let want = expect["plaintext"] as! String
                let got = try codec.decrypt(record)
                XCTAssertEqual(hex(got), want, "case \(name): plaintext")
            }
        }
    }

    func testMatchesEverySharedReplayWindowVerdict() throws {
        let fx = try fixture("replay-window.json")
        requireListed(fx, "replay-window.json")

        // The fixture was generated for a specific window size; a build with a different one
        // would fail cases for a reason unrelated to correctness.
        if let ws = fx["window_size"] as? Int {
            XCTAssertEqual(ws, PacketCodec.replayWindow, "fixture window size vs this build")
        }

        let cases = fx["cases"] as? [[String: Any]] ?? []
        XCTAssertFalse(cases.isEmpty, "fixture file has no cases")

        for c in cases {
            let name = c["name"] as? String ?? "?"
            let seqs = (c["seqs"] as? [NSNumber] ?? []).map { $0.uint64Value }
            let want = c["verdicts"] as? [Bool] ?? []

            // A FRESH window per case — the codec owns the window, so a fresh codec is a
            // fresh window. The key is irrelevant here: no crypto is exercised.
            let codec = PacketCodec(cipher: try PacketCipher(key: Data(count: 32)))
            let got = seqs.map { codec.acceptCounter($0) }

            XCTAssertEqual(got, want, "case \(name): verdicts for seqs \(seqs)")
        }
    }

    /// UDP handshake fragmentation. The reassembler is fed by the NETWORK — out of order,
    /// with duplicates, with gaps, and with whatever an attacker sends — so the malformed
    /// cases matter as much as the happy ones. The failure this pins against is the classic
    /// "works on Wi-Fi, hangs on LTE": IP fragments are dropped on mobile / CGNAT paths,
    /// which is the whole reason the handshake is split at the app layer.
    func testFragmentsReassemblesAndClassifiesEverySharedVector() throws {
        let fx = try fixture("udp-frag.json")
        requireListed(fx, "udp-frag.json")

        XCTAssertEqual(fx["max_chunk"] as? Int, UDPFragmentation.maxChunk,
                       "fixture maxChunk vs this build")
        // The receive bound is pinned separately and is LARGER: bounding receive by the send
        // budget would reject every handshake from a pre-#14 peer.
        XCTAssertEqual(fx["max_chunk_accept"] as? Int, UDPFragmentation.maxChunkAccept,
                       "fixture maxChunkAccept vs this build")
        XCTAssertEqual(fx["max_frags"] as? Int, UDPFragmentation.maxFragments,
                       "fixture maxFragments vs this build")
        // The AuthOK id must be identical in every retained primitive. A different number does
        // not fail loudly — it simply never reassembles a large AuthOK, which presents as a
        // dead server rather than a version mismatch.
        XCTAssertEqual(fx["msg_auth_ok"] as? Int, Int(UDPFragmentation.authOK),
                       "fixture authOK vs this build")

        // ── fragment ────────────────────────────────────────────────────────────
        let frags = fx["fragment"] as? [[String: Any]] ?? []
        XCTAssertFalse(frags.isEmpty, "no fragment cases")
        for c in frags {
            let name = c["name"] as? String ?? "?"
            let msgId = UInt8((c["msg_id"] as! NSNumber).intValue)
            let expect = c["expect"] as! [String: Any]

            if (expect["reject"] as? Bool) == true {
                // The oversize body is megabytes, so the fixture records its SHAPE.
                let len = (c["message_len"] as! NSNumber).intValue
                var big = Data(count: len)
                for i in 0..<len { big[i] = UInt8((i * 31 + 7) % 256) }
                XCTAssertThrowsError(try UDPFragmentation.fragment(messageID: msgId, message: big),
                                     "case \(name): oversize message was fragmented instead of refused")
            } else {
                let msg = try unhex(c["message"] as! String)
                let got = try UDPFragmentation.fragment(messageID: msgId, message: msg).map { hex($0) }
                let want = expect["fragments"] as! [String]
                XCTAssertEqual(got, want, "case \(name): fragments")
            }
        }

        // ── reassemble ──────────────────────────────────────────────────────────
        let res = fx["reassemble"] as? [[String: Any]] ?? []
        XCTAssertFalse(res.isEmpty, "no reassemble cases")
        for c in res {
            let name = c["name"] as? String ?? "?"
            let expect = c["expect"] as! [String: Any]

            // A FRESH reassembler per case.
            let re = UDPFragmentation.Reassembler()
            var completed: Data?
            var rejected = false
            for d in (c["feed"] as! [String]) {
                do {
                    if let got = try re.push(try unhex(d)) { completed = got; break }
                } catch {
                    rejected = true
                    break
                }
            }

            if (expect["reject"] as? Bool) == true {
                XCTAssertTrue(rejected, "case \(name): a malformed fragment was ACCEPTED")
            } else if (expect["incomplete"] as? Bool) == true {
                XCTAssertFalse(rejected, "case \(name): an incomplete message was rejected outright")
                XCTAssertNil(completed, "case \(name): completed a message missing a fragment")
            } else {
                XCTAssertNotNil(completed, "case \(name): never completed (rejected=\(rejected))")
                XCTAssertEqual(hex(completed ?? Data()), expect["message"] as! String,
                               "case \(name): reassembled message")
            }
        }

        // ── classify ────────────────────────────────────────────────────────────
        let cls = fx["classify"] as? [[String: Any]] ?? []
        XCTAssertFalse(cls.isEmpty, "no classify cases")
        for c in cls {
            let name = c["name"] as? String ?? "?"
            let d = try unhex(c["datagram"] as! String)
            let e = c["expect"] as! [String: Bool]
            XCTAssertEqual(UDPFragmentation.isFragment(d), e["is_fragment"]!, "case \(name): is_fragment")
            XCTAssertEqual(UDPFragmentation.isJunk(d), e["is_junk"]!, "case \(name): is_junk")
            XCTAssertEqual(UDPFragmentation.isMTUProbe(d), e["is_mtu_probe"]!, "case \(name): is_mtu_probe")
            XCTAssertEqual(UDPFragmentation.isMTUProbeAck(d), e["is_mtu_probe_ack"]!, "case \(name): is_mtu_probe_ack")
            XCTAssertEqual(UDPFragmentation.isAuthOKFragment(d), e["is_auth_ok"]!, "case \(name): is_auth_ok")
        }
    }

    /// The exact bytes of the in-tunnel MTU report, pinned identically in the Rust, C# and Kotlin
    /// ports. A port that drifts on byte order or the magic makes the server read a nonsense MTU.
    func testCtrlMTUReportMatchesTheSharedVector() {
        // 1280 = 0x0500, big-endian.
        XCTAssertEqual(CtrlFrame.mtuReport(1_280).map { String(format: "%02x", $0) }.joined(),
                       "c19b01020500")
        XCTAssertEqual(CtrlFrame.mtuReport(70_000).map { String(format: "%02x", $0) }.joined(),
                       "c19b0102ffff", "clamped, not wrapped")
        XCTAssertEqual(CtrlFrame.mtuReport(-1).map { String(format: "%02x", $0) }.joined(),
                       "c19b01020000", "clamped, not wrapped")

        // The discriminator that keeps control frames and IP packets apart, in both directions.
        XCTAssertTrue(CtrlFrame.isCtrl(CtrlFrame.mtuReport(1_280)))
        XCTAssertFalse(CtrlFrame.isCtrl(Data([0x45, 0x00, 0x00, 0x28])), "IPv4")
        XCTAssertFalse(CtrlFrame.isCtrl(Data([0x60, 0x00, 0x00, 0x00])), "IPv6")
        XCTAssertFalse(CtrlFrame.isCtrl(Data()), "heartbeat")
    }

    /// Client info (type 2), pinned to the SAME bytes as the Rust and retained C# tests so the
    /// implementations cannot drift:
    /// `[magic][type=2][len=12][verLen=6]["0.7.13"]["linux"]`.
    func testCtrlClientInfoMatchesTheSharedVector() throws {
        let frame = try XCTUnwrap(CtrlFrame.clientInfo(version: "0.7.13", platform: "linux"))
        XCTAssertEqual(frame.map { String(format: "%02x", $0) }.joined(),
                       "c19b020c06302e372e31336c696e7578")

        // The server REJECTS a bad version or platform outright rather than scrubbing it, so a
        // frame it would refuse must not be built here either. These are the shapes that reach a
        // log line, a terminal table and the panel's DOM.
        XCTAssertNil(CtrlFrame.clientInfo(version: "0.7.13\nX", platform: "linux"),
                     "a newline forges a log line")
        XCTAssertNil(CtrlFrame.clientInfo(version: "<b>1.0</b>", platform: "linux"),
                     "markup reaches the panel DOM")
        XCTAssertNil(CtrlFrame.clientInfo(version: "", platform: "linux"))
        XCTAssertNil(CtrlFrame.clientInfo(version: String(repeating: "9", count: 33),
                                          platform: "linux"), "over the 32-byte cap")
        XCTAssertNil(CtrlFrame.clientInfo(version: "0.7.13", platform: "Linux"),
                     "platform must be lowercase")
        XCTAssertNil(CtrlFrame.clientInfo(version: "0.7.13", platform: ""))
        XCTAssertNil(CtrlFrame.clientInfo(version: "0.7.13",
                                          platform: String(repeating: "a", count: 17)),
                     "over the 16-byte cap")

        // Valid non-trivial values must still build.
        XCTAssertNotNil(CtrlFrame.clientInfo(version: "1.0.0-rc1+build.7", platform: "linux"))
        for tag in ["linux", "windows", "macos", "android", "ios", "freebsd", "other"] {
            XCTAssertNotNil(CtrlFrame.clientInfo(version: "0.7.13", platform: tag),
                            "platform \(tag) must be accepted")
        }
        // This build's own tag must be one the server accepts.
        XCTAssertNotNil(CtrlFrame.clientInfo(version: "0.7.13", platform: CtrlFrame.platform))
    }

    /// A pre-#14 peer slices at 1200, which is ABOVE this build's send budget. The reassembler
    /// must bound by ``maxChunkAccept``, not ``maxChunk``, or every legacy handshake is rejected
    /// as `chunkTooLarge`.
    func testLegacyChunksStillReassemble() throws {
        let legacy = 1_200
        XCTAssertGreaterThan(legacy, UDPFragmentation.maxChunk, "the bounds must differ")
        XCTAssertLessThanOrEqual(legacy, UDPFragmentation.maxChunkAccept, "accept must cover legacy")

        let reassembler = UDPFragmentation.Reassembler()
        var out: Data?
        for index in 0..<2 {
            var d = Data(UDPFragmentation.magic)
            d.append(contentsOf: [UDPFragmentation.serverHello, UInt8(index), 2])
            d.append(Data(repeating: 0x4C, count: legacy))
            out = try reassembler.push(d)
            if index == 0 { XCTAssertNil(out, "must not complete on the first fragment") }
        }
        XCTAssertEqual(out?.count, legacy * 2, "legacy message length")
    }
}
